// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoMansSkyRecipies.Data;

namespace NoMansSkyRecipies.Data.Migrations
{
    [DbContext(typeof(RecipiesDbContext))]
    [Migration("20220428105036_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.CraftableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("CraftableItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acid",
                            Value = 188000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aronium",
                            Value = 25000
                        },
                        new
                        {
                            Id = 3,
                            Name = "Circut Board",
                            Value = 916250
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cryo Pump",
                            Value = 1500000
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cryogenic Chamber",
                            Value = 3800000
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dirty Bronze",
                            Value = 25000
                        },
                        new
                        {
                            Id = 7,
                            Name = "Enriched Carbon",
                            Value = 50000
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fusion Accelerant",
                            Value = 1500000
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fusion Ignitor",
                            Value = 15600000
                        },
                        new
                        {
                            Id = 10,
                            Name = "Glass",
                            Value = 200
                        },
                        new
                        {
                            Id = 11,
                            Name = "Goedesite",
                            Value = 150000
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grantine",
                            Value = 25000
                        },
                        new
                        {
                            Id = 13,
                            Name = "Heat Capacitor",
                            Value = 188000
                        },
                        new
                        {
                            Id = 14,
                            Name = "Herox",
                            Value = 25000
                        },
                        new
                        {
                            Id = 15,
                            Name = "Hot Ice",
                            Value = 320000
                        },
                        new
                        {
                            Id = 16,
                            Name = "Lemmium",
                            Value = 25000
                        },
                        new
                        {
                            Id = 17,
                            Name = "Liquid Explosive",
                            Value = 800500
                        },
                        new
                        {
                            Id = 18,
                            Name = "Living Glass",
                            Value = 566000
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lubricant",
                            Value = 110000
                        },
                        new
                        {
                            Id = 20,
                            Name = "Magno-Gold",
                            Value = 25000
                        },
                        new
                        {
                            Id = 21,
                            Name = "Nitrogen Salt",
                            Value = 50000
                        },
                        new
                        {
                            Id = 22,
                            Name = "Organic Catalyst",
                            Value = 320000
                        },
                        new
                        {
                            Id = 23,
                            Name = "Poly Fibre",
                            Value = 130000
                        },
                        new
                        {
                            Id = 24,
                            Name = "Portable Reactor",
                            Value = 4200000
                        },
                        new
                        {
                            Id = 25,
                            Name = "Quantum Processor",
                            Value = 5200000
                        },
                        new
                        {
                            Id = 26,
                            Name = "Semiconductor",
                            Value = 400000
                        },
                        new
                        {
                            Id = 27,
                            Name = "Stasis Device",
                            Value = 15600000
                        },
                        new
                        {
                            Id = 28,
                            Name = "Superconductor",
                            Value = 1500000
                        },
                        new
                        {
                            Id = 29,
                            Name = "Thermic Condensate",
                            Value = 50000
                        },
                        new
                        {
                            Id = 30,
                            Name = "Unstable Gel",
                            Value = 50000
                        },
                        new
                        {
                            Id = 31,
                            Name = "Iridesite",
                            Value = 150000
                        });
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.ImageContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageContainers");
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.NeededResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CraftableItemId")
                        .HasColumnType("int");

                    b.Property<int>("NeededAmount")
                        .HasColumnType("int");

                    b.Property<int?>("RawResourceId")
                        .HasColumnType("int");

                    b.Property<int>("RecipieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CraftableItemId");

                    b.HasIndex("RawResourceId");

                    b.HasIndex("RecipieId");

                    b.ToTable("NeededResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NeededAmount = 25,
                            RawResourceId = 10,
                            RecipieId = 1
                        },
                        new
                        {
                            Id = 2,
                            NeededAmount = 600,
                            RawResourceId = 7,
                            RecipieId = 1
                        },
                        new
                        {
                            Id = 3,
                            NeededAmount = 50,
                            RawResourceId = 12,
                            RecipieId = 2
                        },
                        new
                        {
                            Id = 4,
                            NeededAmount = 50,
                            RawResourceId = 9,
                            RecipieId = 2
                        },
                        new
                        {
                            Id = 5,
                            CraftableItemId = 13,
                            NeededAmount = 1,
                            RecipieId = 3
                        },
                        new
                        {
                            Id = 6,
                            CraftableItemId = 23,
                            NeededAmount = 1,
                            RecipieId = 3
                        },
                        new
                        {
                            Id = 7,
                            CraftableItemId = 15,
                            NeededAmount = 1,
                            RecipieId = 4
                        },
                        new
                        {
                            Id = 8,
                            CraftableItemId = 29,
                            NeededAmount = 1,
                            RecipieId = 4
                        },
                        new
                        {
                            Id = 9,
                            CraftableItemId = 4,
                            NeededAmount = 1,
                            RecipieId = 5
                        },
                        new
                        {
                            Id = 10,
                            CraftableItemId = 18,
                            NeededAmount = 1,
                            RecipieId = 5
                        },
                        new
                        {
                            Id = 11,
                            NeededAmount = 100,
                            RawResourceId = 14,
                            RecipieId = 6
                        },
                        new
                        {
                            Id = 12,
                            NeededAmount = 50,
                            RawResourceId = 15,
                            RecipieId = 6
                        },
                        new
                        {
                            Id = 13,
                            NeededAmount = 250,
                            RawResourceId = 16,
                            RecipieId = 7
                        },
                        new
                        {
                            Id = 14,
                            NeededAmount = 50,
                            RawResourceId = 3,
                            RecipieId = 7
                        },
                        new
                        {
                            Id = 15,
                            CraftableItemId = 22,
                            NeededAmount = 1,
                            RecipieId = 8
                        },
                        new
                        {
                            Id = 16,
                            CraftableItemId = 21,
                            NeededAmount = 1,
                            RecipieId = 8
                        },
                        new
                        {
                            Id = 17,
                            CraftableItemId = 25,
                            NeededAmount = 1,
                            RecipieId = 9
                        },
                        new
                        {
                            Id = 18,
                            CraftableItemId = 24,
                            NeededAmount = 1,
                            RecipieId = 9
                        },
                        new
                        {
                            Id = 19,
                            CraftableItemId = 11,
                            NeededAmount = 1,
                            RecipieId = 9
                        },
                        new
                        {
                            Id = 20,
                            NeededAmount = 40,
                            RawResourceId = 6,
                            RecipieId = 10
                        },
                        new
                        {
                            Id = 21,
                            CraftableItemId = 6,
                            NeededAmount = 1,
                            RecipieId = 11
                        },
                        new
                        {
                            Id = 22,
                            CraftableItemId = 16,
                            NeededAmount = 1,
                            RecipieId = 11
                        },
                        new
                        {
                            Id = 23,
                            CraftableItemId = 14,
                            NeededAmount = 1,
                            RecipieId = 11
                        },
                        new
                        {
                            Id = 24,
                            NeededAmount = 50,
                            RawResourceId = 9,
                            RecipieId = 12
                        },
                        new
                        {
                            Id = 25,
                            NeededAmount = 50,
                            RawResourceId = 4,
                            RecipieId = 12
                        },
                        new
                        {
                            Id = 26,
                            NeededAmount = 100,
                            RawResourceId = 6,
                            RecipieId = 13
                        },
                        new
                        {
                            Id = 27,
                            NeededAmount = 200,
                            RawResourceId = 17,
                            RecipieId = 13
                        },
                        new
                        {
                            Id = 28,
                            NeededAmount = 50,
                            RawResourceId = 9,
                            RecipieId = 14
                        },
                        new
                        {
                            Id = 29,
                            NeededAmount = 50,
                            RawResourceId = 1,
                            RecipieId = 14
                        },
                        new
                        {
                            Id = 30,
                            CraftableItemId = 7,
                            NeededAmount = 1,
                            RecipieId = 15
                        },
                        new
                        {
                            Id = 31,
                            CraftableItemId = 21,
                            NeededAmount = 1,
                            RecipieId = 15
                        },
                        new
                        {
                            Id = 32,
                            NeededAmount = 100,
                            RawResourceId = 14,
                            RecipieId = 16
                        },
                        new
                        {
                            Id = 33,
                            NeededAmount = 50,
                            RawResourceId = 20,
                            RecipieId = 16
                        },
                        new
                        {
                            Id = 34,
                            CraftableItemId = 1,
                            NeededAmount = 1,
                            RecipieId = 17
                        },
                        new
                        {
                            Id = 35,
                            CraftableItemId = 30,
                            NeededAmount = 1,
                            RecipieId = 17
                        },
                        new
                        {
                            Id = 36,
                            CraftableItemId = 10,
                            NeededAmount = 5,
                            RecipieId = 18
                        },
                        new
                        {
                            Id = 37,
                            CraftableItemId = 19,
                            NeededAmount = 1,
                            RecipieId = 18
                        },
                        new
                        {
                            Id = 38,
                            NeededAmount = 50,
                            RawResourceId = 5,
                            RecipieId = 19
                        },
                        new
                        {
                            Id = 39,
                            NeededAmount = 400,
                            RawResourceId = 8,
                            RecipieId = 19
                        },
                        new
                        {
                            Id = 40,
                            NeededAmount = 50,
                            RawResourceId = 9,
                            RecipieId = 20
                        },
                        new
                        {
                            Id = 41,
                            NeededAmount = 50,
                            RawResourceId = 13,
                            RecipieId = 20
                        },
                        new
                        {
                            Id = 42,
                            NeededAmount = 250,
                            RawResourceId = 11,
                            RecipieId = 21
                        },
                        new
                        {
                            Id = 43,
                            NeededAmount = 50,
                            RawResourceId = 3,
                            RecipieId = 21
                        },
                        new
                        {
                            Id = 44,
                            CraftableItemId = 29,
                            NeededAmount = 1,
                            RecipieId = 22
                        },
                        new
                        {
                            Id = 45,
                            CraftableItemId = 7,
                            NeededAmount = 1,
                            RecipieId = 22
                        },
                        new
                        {
                            Id = 46,
                            NeededAmount = 100,
                            RawResourceId = 2,
                            RecipieId = 23
                        },
                        new
                        {
                            Id = 47,
                            NeededAmount = 200,
                            RawResourceId = 18,
                            RecipieId = 23
                        },
                        new
                        {
                            Id = 48,
                            CraftableItemId = 8,
                            NeededAmount = 1,
                            RecipieId = 24
                        },
                        new
                        {
                            Id = 49,
                            CraftableItemId = 17,
                            NeededAmount = 1,
                            RecipieId = 24
                        },
                        new
                        {
                            Id = 50,
                            CraftableItemId = 28,
                            NeededAmount = 1,
                            RecipieId = 25
                        },
                        new
                        {
                            Id = 51,
                            CraftableItemId = 3,
                            NeededAmount = 1,
                            RecipieId = 25
                        },
                        new
                        {
                            Id = 52,
                            CraftableItemId = 29,
                            NeededAmount = 1,
                            RecipieId = 26
                        },
                        new
                        {
                            Id = 53,
                            CraftableItemId = 21,
                            NeededAmount = 1,
                            RecipieId = 26
                        },
                        new
                        {
                            Id = 54,
                            CraftableItemId = 31,
                            NeededAmount = 1,
                            RecipieId = 27
                        },
                        new
                        {
                            Id = 55,
                            CraftableItemId = 5,
                            NeededAmount = 1,
                            RecipieId = 27
                        },
                        new
                        {
                            Id = 56,
                            CraftableItemId = 25,
                            NeededAmount = 1,
                            RecipieId = 27
                        },
                        new
                        {
                            Id = 57,
                            CraftableItemId = 26,
                            NeededAmount = 1,
                            RecipieId = 28
                        },
                        new
                        {
                            Id = 58,
                            CraftableItemId = 7,
                            NeededAmount = 1,
                            RecipieId = 28
                        },
                        new
                        {
                            Id = 59,
                            NeededAmount = 250,
                            RawResourceId = 19,
                            RecipieId = 29
                        },
                        new
                        {
                            Id = 60,
                            NeededAmount = 50,
                            RawResourceId = 3,
                            RecipieId = 29
                        },
                        new
                        {
                            Id = 61,
                            NeededAmount = 200,
                            RawResourceId = 2,
                            RecipieId = 30
                        },
                        new
                        {
                            Id = 62,
                            CraftableItemId = 12,
                            NeededAmount = 1,
                            RecipieId = 31
                        },
                        new
                        {
                            Id = 63,
                            CraftableItemId = 20,
                            NeededAmount = 1,
                            RecipieId = 31
                        },
                        new
                        {
                            Id = 64,
                            CraftableItemId = 2,
                            NeededAmount = 1,
                            RecipieId = 31
                        });
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.RawResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("RawResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("RawResourceTypeId");

                    b.ToTable("RawResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ammonia",
                            RawResourceTypeId = 1,
                            Value = 62
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cactus Flesh",
                            RawResourceTypeId = 2,
                            Value = 28
                        },
                        new
                        {
                            Id = 3,
                            Name = "Condenced Carbon",
                            RawResourceTypeId = 4,
                            Value = 24
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dioxite",
                            RawResourceTypeId = 1,
                            Value = 62
                        },
                        new
                        {
                            Id = 5,
                            Name = "Faecium",
                            RawResourceTypeId = 2,
                            Value = 30
                        },
                        new
                        {
                            Id = 6,
                            Name = "Frost Crystal",
                            RawResourceTypeId = 2,
                            Value = 12
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fungal Mold",
                            RawResourceTypeId = 2,
                            Value = 16
                        },
                        new
                        {
                            Id = 8,
                            Name = "GammaRoot",
                            RawResourceTypeId = 2,
                            Value = 16
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ionized Cobalt",
                            RawResourceTypeId = 4,
                            Value = 401
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mordite",
                            RawResourceTypeId = 2,
                            Value = 40
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nitrogen",
                            RawResourceTypeId = 3,
                            Value = 20
                        },
                        new
                        {
                            Id = 12,
                            Name = "Paraffinium",
                            RawResourceTypeId = 1,
                            Value = 62
                        },
                        new
                        {
                            Id = 13,
                            Name = "Phosphorus",
                            RawResourceTypeId = 1,
                            Value = 62
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pure Ferrite",
                            RawResourceTypeId = 4,
                            Value = 28
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pyrite",
                            RawResourceTypeId = 1,
                            Value = 62
                        },
                        new
                        {
                            Id = 16,
                            Name = "Radon",
                            RawResourceTypeId = 3,
                            Value = 20
                        },
                        new
                        {
                            Id = 17,
                            Name = "Solanium",
                            RawResourceTypeId = 2,
                            Value = 70
                        },
                        new
                        {
                            Id = 18,
                            Name = "Star Bulb",
                            RawResourceTypeId = 2,
                            Value = 32
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sulphurine",
                            RawResourceTypeId = 3,
                            Value = 20
                        },
                        new
                        {
                            Id = 20,
                            Name = "Uranium",
                            RawResourceTypeId = 1,
                            Value = 62
                        });
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.RawResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResourceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ResourceTypeName = "Mined mineral"
                        },
                        new
                        {
                            Id = 2,
                            ResourceTypeName = "Harvested plant"
                        },
                        new
                        {
                            Id = 3,
                            ResourceTypeName = "Atospheric gas"
                        },
                        new
                        {
                            Id = 4,
                            ResourceTypeName = "Compressed mineral"
                        });
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.Recipie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResultingItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultingItemId");

                    b.ToTable("Recipies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ResultingItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            ResultingItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            ResultingItemId = 3
                        },
                        new
                        {
                            Id = 4,
                            ResultingItemId = 4
                        },
                        new
                        {
                            Id = 5,
                            ResultingItemId = 5
                        },
                        new
                        {
                            Id = 6,
                            ResultingItemId = 6
                        },
                        new
                        {
                            Id = 7,
                            ResultingItemId = 7
                        },
                        new
                        {
                            Id = 8,
                            ResultingItemId = 8
                        },
                        new
                        {
                            Id = 9,
                            ResultingItemId = 9
                        },
                        new
                        {
                            Id = 10,
                            ResultingItemId = 10
                        },
                        new
                        {
                            Id = 11,
                            ResultingItemId = 11
                        },
                        new
                        {
                            Id = 12,
                            ResultingItemId = 12
                        },
                        new
                        {
                            Id = 13,
                            ResultingItemId = 13
                        },
                        new
                        {
                            Id = 14,
                            ResultingItemId = 14
                        },
                        new
                        {
                            Id = 15,
                            ResultingItemId = 15
                        },
                        new
                        {
                            Id = 16,
                            ResultingItemId = 16
                        },
                        new
                        {
                            Id = 17,
                            ResultingItemId = 17
                        },
                        new
                        {
                            Id = 18,
                            ResultingItemId = 18
                        },
                        new
                        {
                            Id = 19,
                            ResultingItemId = 19
                        },
                        new
                        {
                            Id = 20,
                            ResultingItemId = 20
                        },
                        new
                        {
                            Id = 21,
                            ResultingItemId = 21
                        },
                        new
                        {
                            Id = 22,
                            ResultingItemId = 22
                        },
                        new
                        {
                            Id = 23,
                            ResultingItemId = 23
                        },
                        new
                        {
                            Id = 24,
                            ResultingItemId = 24
                        },
                        new
                        {
                            Id = 25,
                            ResultingItemId = 25
                        },
                        new
                        {
                            Id = 26,
                            ResultingItemId = 26
                        },
                        new
                        {
                            Id = 27,
                            ResultingItemId = 27
                        },
                        new
                        {
                            Id = 28,
                            ResultingItemId = 28
                        },
                        new
                        {
                            Id = 29,
                            ResultingItemId = 29
                        },
                        new
                        {
                            Id = 30,
                            ResultingItemId = 30
                        },
                        new
                        {
                            Id = 31,
                            ResultingItemId = 31
                        });
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.CraftableItem", b =>
                {
                    b.HasOne("NoMansSkyRecipies.Data.Entities.ImageContainer", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.NeededResource", b =>
                {
                    b.HasOne("NoMansSkyRecipies.Data.Entities.CraftableItem", "CraftableItem")
                        .WithMany()
                        .HasForeignKey("CraftableItemId");

                    b.HasOne("NoMansSkyRecipies.Data.Entities.RawResource", "RawResource")
                        .WithMany()
                        .HasForeignKey("RawResourceId");

                    b.HasOne("NoMansSkyRecipies.Data.Entities.Recipie", "Recipie")
                        .WithMany("NeededResources")
                        .HasForeignKey("RecipieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.RawResource", b =>
                {
                    b.HasOne("NoMansSkyRecipies.Data.Entities.ImageContainer", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("NoMansSkyRecipies.Data.Entities.RawResourceType", "RawResourceType")
                        .WithMany("RawResources")
                        .HasForeignKey("RawResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoMansSkyRecipies.Data.Entities.Recipie", b =>
                {
                    b.HasOne("NoMansSkyRecipies.Data.Entities.CraftableItem", "ResultingItem")
                        .WithMany("Recipies")
                        .HasForeignKey("ResultingItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
